---
applications:
- name: builders
  routes:
    - route: builders.run.platform.nirdhost.com
    - route: thebldrz.com
    - route: www.thebldrz.com
  services:
    - builders_production
  command: bundle exec rake cf:on_first_instance db:migrate && bundle exec rails s -p $PORT -e $RAILS_ENV
  memory: 512MB
  instances: 1
